version: "3.6"

services:
  ch-sub-2:
    container_name: ch-sub-2
    image: yandex/clickhouse-server
    ports:
      - 92:9000
      - 82:8123
    volumes:
      - type: volume
        source: ch-sub-2-data
        target: /var/lib/clickhouse
      - type: volume
        source: ch-sub-2-logs
        target: /var/log/clickhouse-server
      - ./config/sub-2-config.xml:/etc/clickhouse-server/config.xml
  zk-3:
    container_name: zk-3
    hostname: zk-3
    image: bitnami/zookeeper:3.6.2
    ports:
      - 21811:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zk1:2888:3888

volumes:
  ch-sub-2-data:
  ch-sub-2-logs:


